#!/bin/csh
setenv DISPLAY :5
setenv _R_CHECK_CRAN_INCOMING_ true
setenv _R_CHECK_FORCE_SUGGESTS_ FALSE
setenv _R_CHECK_VC_DIRS_ TRUE
setenv _R_CHECK_UNSAFE_CALLS_ TRUE
setenv _R_CHECK_TIMINGS_ 10
setenv _R_CHECK_INSTALL_DEPENDS_ TRUE
setenv _R_CHECK_SUGGESTS_ONLY_ TRUE
setenv _R_CHECK_NO_RECOMMENDED_ TRUE
setenv _R_CHECK_SUBDIRS_NOCASE_ TRUE
setenv _R_CHECK_EXECUTABLES_EXCLUSIONS_ false
setenv _R_CHECK_ALWAYS_LOG_VIGNETTE_OUTPUT_ true
setenv _R_CHECK_DOC_SIZES2_ true
setenv _R_CHECK_XREFS_USE_ALIASES_FROM_CRAN_ true
setenv R_C_BOUNDS_CHECK yes
setenv R_LIBS ~/R/test-2.16:~/R/test-2.15:~/R/BioC-2.11:~/R/test-Omegahat
foreach f ($*)
~/R/R-devel-lo/bin/R CMD check --as-cran --timings $f
end
