#!/bin/csh
setenv DISPLAY :5
setenv TMPDIR ~/R/packages/BioC/3.1/tmp
limit cputime 30m
setenv R_LIBS ~/R/BioC-3.1
setenv _R_CHECK_DEPRECATED_DEFUNCT_ true
#setenv R_C_BOUNDS_CHECK yes
set path = ($path /data/blackswan/ripley/extras/bin)


nohup make -j32 -k check >&! check_log
