#! /bin/csh
set path=(/usr/local/bin /usr/local/texlive/2011/bin/x86_64-linux /usr/sbin $path /usr/lib64/openmpi/bin)
cd ~/R/svn/R-devel
svn up
cd ~/R/R-devel
make
cd R/packages
./update
/data/gannet/ripley/R/R-devel/bin/Rscript updates.R
cd tests-devel
make unpack
./script
cat check_log
echo 'packaging'
make package
echo 'summarizing'
make summary
echo 'done'
