#!/bin/bash -x
# This script is run daily from cron in the prerelease period
# It is assumed that version numbers etc. are already set up

LOCALDIR=/usr/local/src/pd
FTPDIR=$HOME/public_html/R-pre
# ---------- no changes should be necessary below this line
cd $LOCALDIR/r-release-branch
umask 022
cd R
svn up || exit 1
#export CRAN_RSYNC='cran.at.r-project.org::CRAN'
tools/rsync-recommended || \
(sleep 60; tools/rsync-recommended) || \
(sleep 60; tools/rsync-recommended) || \
(sleep 60; tools/rsync-recommended) #|| \
# exit 1
# Kludge to avoid rebuilding java stuff with insufficient
# toolchain
touch doc/html/search/*.class 
cd ..
rm -rf BUILD-dist
mkdir BUILD-dist
cd BUILD-dist
../R/configure --enable-maintainer-mode || exit 1
(cd ../R ; svn commit -m 'maintainer-mode changes')
make -j4 || exit 1
make dist || exit 1
RNOW=`echo R*.tar.gz`
cp R*.tar.gz $FTPDIR
ln -f $FTPDIR/$RNOW $FTPDIR/R-latest.tar.gz
find $FTPDIR -name R-\*.gz -mmin +4200 -exec rm {} \;
