#!/bin/bash -x
# This script forks R-x-y-branch from the trunk and updates the
# local checkout directories accordingly
#
# Running the script initiates Grand Feature Freeze
#
# For now, the next three lines must be edited for each
# major release.
#
BRANCH=R-2-6-branch
VERSION=2.6.0
NEXT=2.7.0
LOCALDIR=/usr/local/src/pd
#--- no changes should be necessary below this line
export REPOS=https://svn.r-project.org/R
svn cp -m"Create $BRANCH" $REPOS/trunk $REPOS/branches/$BRANCH
cd $LOCALDIR/r-release-branch/
umask 022
cd R
svn switch $REPOS/branches/$BRANCH
svn up || exit 1
echo "$VERSION alpha" > VERSION
aclocal -I m4 
svn commit -m "go to $VERSION alpha"
cd $LOCALDIR/r-devel
umask 022
cd R
svn up || exit 1
echo "$NEXT Under development (unstable)" > VERSION
aclocal -I m4 
svn commit -m "go to $NEXT devel"
