#!/bin/bash
LOCALDIR=$HOME
PUBDIR=$HOME/R-pre
CRANDIR=cran.r-project.org:/srv/ftp/pub/R/src/base-prerelease
# -----
cd $PUBDIR
for i in 8 7 6 5 4 3 2 1 0 ; do mv -f build-prerelease.log.$i build-prerelease.log.$((i+1)) ; done 
cp -f build-prerelease.log build-prerelease.log.0
for i in 8 7 6 5 4 3 2 1 0 ; do mv -f build-devel.log.$i build-devel.log.$((i+1)) ; done 
cp -f build-devel.log build-devel.log.0
rsync -aOvuz --no-p --delete $PUBDIR/ $CRANDIR
