#!/bin/bash -x
# This script sets the VERSION file and commits it
# It is run from cron at Feature Freeze and Code Freeze
LOCALDIR=$HOME
# -- no changes necessary below this line
cd $LOCALDIR/r-release-branch
umask 022
cd R
svn up || exit 1
echo $* > VERSION
aclocal -I m4 --force
autoconf --force
svn commit -m "go to $*"
