#!/bin/bash -x
# This script sets the VERSION file andi, optionally, the VERSION-NICK
# and then commits the changes
# It is run from cron at Feature Freeze and Code Freeze
LOCALDIR=$HOME
# -- no changes necessary below this line
cd $LOCALDIR/r-release-branch
umask 022
cd R
svn up || exit 1
echo $1 > VERSION
if [ x"$2" != x ]; then echo $2 > VERSION-NICK ; fi
aclocal -I m4 --force
autoconf --force
svn commit -m "go to $*"
