.SUFFICES: .out .log

RDEV=/home/ripley/R/cc/bin/R
RLIBS=/home/ripley/R/Lib32
BACKUP=../tests32-keep

## hit CPU limit
AGSDest-OPTS = --no-vignettes
ARAMIS-OPTS = --no-vignettes
BB-OPTS = --no-tests --no-vignettes
BMS-OPTS = --no-vignettes
ChemoSpec-OPTS = --no-build-vignettes
CONOR-OPTS = --no-examples
CDVine-OPTS = --no-build-vignettes
CORE-OPTS = --no-build-vignettes
DAKS-OPTS = --no-vignettes
DDD-OPTS = --no-examples
DOBAD-OPTS = --no-vignettes
GOGANPA-OPTS = --no-examples
GSM-OPTS = --no-examples
GenABEL-OPTS = --no-examples
HiveR-OPTS = --no-vignettes
LaplacesDemon-OPTS = --no-vignettes
LogConcDEAD-OPTS = --no-vignettes
MetabolAnalyze-OPTS = --no-examples
ModelMap-OPTS = --no-vignettes
NMF-OPTS = --no-tests --no-vignettes
PAGI-OPTS = --no-vignettes
PerformanceAnalytics-OPTS = --no-vignettes
#RFinanceYJ-OPTS = --no-examples
SNPRelate-OPTS = --no-examples --no-tests --no-vignettes
SpatialVX-OPTS = --no-examples
STAR-OPTS = --no-vignettes
SamplingStrata-OPTS = --no-vignettes
Sim.DiffProc-OPTS = --no-examples --no-tests
StatMatch-OPTS = --no-vignettes
TriMatch-OPTS = --no-vignettes
VGAM-OPTS = --no-vignettes
ZeligGAM-OPTS = --no-vignettes
abc-OPTS = --no-vignettes
adehabitatLT-OPTS = --no-examples --no-vignettes
amei-OPTS = --no-vignettes
amer-OPTS = --no-tests --no-vignettes
apcluster-OPTS = --no-vignettes
aspect-OPTS = --no-vignettes
bayesPop-OPTS = --no-tests
bcool-OPTS= --no-vignettes
bfp-OPTS = --no-tests
caret-OPTS = --no-vignettes
copula-OPTS = --no-vignettes
coxphf-OPTS = --no-examples
crimCV-OPTS = --no-examples
crs-OPTS = --no-vignettes
dismo-OPTS = --no-vignettes
dse-OPTS = --no-tests
eqtl-OPTS = --no-examples
expands-OPTS = --no-vignettes
expectreg-OPTS = --no-examples --no-vignettes --no-tests
fanplot-OPTS = --no-vignettes
fbRanks-OPTS = --no-vignettes
fda-OPTS = --no-examples
flexclust-OPTS = --no-tests
flexmix-OPTS = --no-build-vignettes
geiger-OPTS = --no-vignettes
geozoo-OPTS = --no-examples
iSubpathwayMiner-OPTS = --no-vignettes
lokern-OPTS = --no-examples --no-tests
lossDev-OPTS = --no-vignettes
marked-OPTS = --no-examples
mcmc-OPTS = --no-build-vignettes
mediation-OPTS = --no-vignettes
micEconCES-OPTS = --no-tests --no-vignettes
modTempEff-OPTS = --no-vignettes
monomvn-OPTS = --no-examples
move-OPTS = --no-build-vignettes
nFactors-OPTS = --no-vignettes
netweavers-OPTS = --no-vignettes
np-OPTS = --no-examples --no-vignettes
nsRFA-OPTS = --no-vignettes
phangorn-OPTS = --no-vignettes
phylosim-OPTS = --no-vignettes
pomp-OPTS = --no-tests --no-vignettes
psych-OPTS = --no-vignettes
psychomix-OPTS = --no-vignettes
pvclust-OPTS = --no-examples
rWMBAT-OPTS = --no-examples
rattle-OPTS = --no-examples
rebmix-OPTS = --no-vignettes
remMap-OPTS = --no-examples
robustlmm-OPTS = --no-tests
rphast-OPTS = --no-examples --no-tests --no-vignettes
rtfbs-OPTS = --no-examples --no-tests --no-vignettes
secr-OPTS = --no-examples
seriation-OPTS = --no-examples --no-vignettes
speedglm-OPTS = --no-examples
speff2trial-OPTS = --no-examples
spikeSlabGAM-OPTS = --no-examples --no-vignettes
surface-OPTS = --no-vignettes
tgp-OPTS = --no-examples --no-vignettes
twang-OPTS = --no-vignettes
unmarked-OPTS = --no-vignettes
vines-OPTS = --no-tests
widals-OPTS = --no-vignettes

## multicore
adegenet-OPTS = --no-vignettes
multicore-OPTS = --no-examples
mboost-OPTS = --no-vignettes
spikeSlabGAM-OPTS = --no-examples --no-vignettes

## OpenMP
sme-OPTS = --no-examples --no-vignettes --no-tests

## slow/broken web access
DSPRqtl-OPTS = --no-vignettes
NCBI2R-OPTS = --no-examples
RLastFM-OPTS = --no-examples
TSgetSymbol-OPTS = --no-examples --no-vignettes
atmi-OPTS = --no-examples
celsius-OPTS = --no-examples
speedglm-OPTS = --no-examples
elliptic-OPTS = --no-vignettes
misc3d-OPTS = --no-examples
gstudio-OPTS = --no-vignettes
#XML-OPTS = --no-examples

## tries to use RMySQL
vegdata-OPTS = --no-vignettes
TSdata-OPTS = --no-vignettes

DSL-OPTS = --no-vignettes
vegan-OPTS = --no-build-vignettes

## needs Amelia
cem-OPTS = --no-vignettes


## crash etc
FracSim-OPTS=--no-examples

include Makefile.fakes

RGL_USERS = \
  AER.out ChemoSpec.out DiceDesign.out DiceView.out \
  DirichletReg.out ENmisc.out FieldSim.out GeoXp.out HiveR.out \
  KernSmoothIRT.out LMERConvenienceFunctions.out MCMCglmm.out MSQC.out \
  Morpho.out NeatMap.out R330.out RcmdrPlugin.mosaic.out Rknots.out SPOT.out StatDA.out \
  StructR.out VDA.out VecStatGraphs3D.out WMTregions.out YplantQMC.out \
  abcdeFBA.out alphashape3d.out bios2mds.out bpca.out candisc.out caret.out \
  cems.out compositions.out curvHDR.out depth.out dti.out edrGraphicalTools.out \
  feature.out genridge.out geomorph.out grt.out heplots.out hgam.out hiPOD.out \
  homals.out kml3d.out ks.out lle.out longitudinalData.out misc3d.out \
  mixOmics.out msr.out pca3d.out phangorn.out phytools.out ptinpoly.out \
  qpcR.out raster.out rasterVis.out rgl.out seewave.out shapes.out sm.out \
  smacof.out spatgraphs.out sphereplot.out tolerance.out vcdExtra.out \
  visreg.out



%.out: %.log
	@echo $* ...
	-+@R_LIBS=$(RLIBS) MAKE=make MAKEFLAGS= time $(RDEV) CMD check $(R_OPTS) -l $(RLIBS) --install=check:$*.log $($*-OPTS) $* > $@ 2>&1
	@echo ... $* done

all:
	@$(MAKE) -k install
	@DISPLAY=:5 gmake -k check

install:
	@$(RDEV) --slave -f swallow.R

installn:
	@$(RDEV) --slave -f swallow-parallel.R

LOGS=${shell ls *.log}
check: $(LOGS:.log=.out)

backup:
	@mkdir -p $(BACKUP)
	@cp -p Makefile script script-for-rgl2 pkgdiff common.R swallow*.R *.out *.log $(BACKUP)

package: summary timing
	@chmod 644 */DESCRIPTION
	@for f in *.out; do \
	  cp `basename $$f .out`/DESCRIPTION `basename $$f .out`.Rcheck/00package.dcf; \
	done
	@gtar jcf Sparc.tar.bz2 *.Rcheck/00check.log *.Rcheck/00install.out *.Rcheck/00package.dcf
	@scp -q Sparc.tar.bz2 gannet:/data/gannet/Rlogs

summary:
	@Rscript ../summary.R
	@scp -pq check.csv gannet:/data/gannet/Rlogs/Sparc-check.csv

timing:
	@Rscript ../check_times.R
	@scp -pq timings.tab gannet:/data/gannet/Rlogs/Sparc-times.tab

rgl-clean:
	@rm -rf $(RGL_USERS)

rgl-make:
	./script-for-rgl2 $(RGL_USERS)

clean:
	find * -type d -exec rm -rf {} \;
	rm -f *.in

veryclean: clean
	rm -f *.out

rm-recommended:
	rm -rf KernSmooth.* MASS.* Matrix.* boot.* class.* cluster.* \
	  codetools.* foreign.* lattice.* mgcv.* nlme.* nnet.* \
	  rpart.log rpart.out spatial.* survival.*

cp-recommended:
	(cd ../tests-pre-keep; cp -p KernSmooth.out MASS.out Matrix.out \
	  boot.out class.out cluster.out \
	  codetools.out foreign.out lattice.out mgcv.out nlme.out nnet.out \
	  rpart.out spatial.out survival.out ../tests32)
