#!/bin/csh
setenv DISPLAY :5
limit cputime 90m
limit memorysize 8000m
setenv LC_CTYPE en_GB.UTF-8
setenv _R_CHECK_TIMINGS_ 10
setenv _R_CHECK_INSTALL_DEPENDS_ TRUE
setenv _R_CHECK_SUGGESTS_ONLY_ TRUE
setenv _R_CHECK_NO_RECOMMENDED_ TRUE
setenv _R_CHECK_DEPRECATED_DEFUNCT_ true
nohup gmake -j10 -k check >&! check_log
