#!/bin/csh
setenv DISPLAY :5
limit cputime 30m
#limit memoryuse 2000m
setenv LC_CTYPE en_GB.UTF-8
setenv _R_CHECK_TIMINGS_ 10
setenv _R_CHECK_INSTALL_DEPENDS_ TRUE
setenv _R_CHECK_SUGGESTS_ONLY_ TRUE
setenv _R_CHECK_NO_RECOMMENDED_ TRUE
setenv R_PARALLEL_PORT random
#nohup gmake -k check0 >&! check0_log
nohup gmake -j20 -k check >&! check_log
