#!/bin/csh
setenv DISPLAY :5
limit cputime 30m
#limit memoryuse 2000m
setenv LC_CTYPE en_GB.UTF-8
setenv _R_CHECK_TIMINGS_ 10
setenv _R_CHECK_INSTALL_DEPENDS_ TRUE
setenv _R_CHECK_SUGGESTS_ONLY_ TRUE
setenv _R_CHECK_NO_RECOMMENDED_ TRUE
setenv R_PARALLEL_PORT random
setenv _R_CHECK_DEPRECATED_DEFUNCT_ true
setenv _R_CHECK_REPLACING_IMPORTS_ true

setenv _R_CHECK_DOC_SIZES_ false
nohup gmake -j20 -k RDEV=Rgcc Rcpp.out RcppClassic.out RcppArmadillo.out RcppEigen.out Kmisc.out >&! check_log

unsetenv _R_CHECK_DOC_SIZES_
setenv _R_CHECK_DOC_SIZES2_ true
nohup gmake -j20 -k check >>&! check_log
