#! /bin/csh
set path=(/usr/local/bin /usr/local/texbin ~/bin /usr/sbin $path)
setenv PKG_CONFIG_PATH /usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig

cd ~/R/svn/R-3-0-branch
svn up
tools/rsync-recommended
cd ~/R/R-patched
make
cd R/packages
./update
/data/gannet/ripley/R/R-patched/bin/Rscript unavailable.R
env DISPLAY=:5 /data/gannet/ripley/R/R-patched/bin/Rscript updates.R
cd tests
make unpack
./script
cat check_log
