#! /bin/csh
set path=(/usr/local/bin /usr/local/texlive/2012/bin/x86_64-linux /usr/sbin $path)
cd ~/R/svn/R-devel
svn up
tools/rsync-recommended
cd ~/R/R-devel
make
cd ~/R/R-clang
make
cd ~/R/svn/R-3-0-branch
svn up
cd ~/R/R-patched
tools/rsync-recommended
make
cd R/packages
./update
#/data/gannet/ripley/R/R-devel/bin/Rscript updates.R
env DISPLAY=:5 /data/gannet/ripley/R/R-patched/bin/Rscript updates.R
/data/gannet/ripley/R/R-patched/bin/Rscript unavailable.R
env DISPLAY=:5 /data/gannet/ripley/R/R-clang/bin/Rscript updates.R
cd tests-devel
make unpack
./script
cat check_log
cd tests-clang
make unpack
./script
cat check_log
echo 'packaging'
make package
#echo 'summarizing'
#make summary
echo 'done'
