#! /bin/csh
set path=(/usr/local/bin /usr/local/texbin /usr/sbin $path)
setenv PKG_CONFIG_PATH /usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig
cd ~/R/svn/R-devel
svn up
tools/rsync-recommended
cd ~/R/R-clang
make
cd R/packages
./update
env DISPLAY=:5 /data/gannet/ripley/R/R-clang/bin/Rscript updates.R
/data/gannet/ripley/R/R-clang/bin/Rscript unavailable.R
cd tests-clang
make unpack
./script
cat check_log
echo 'packaging'
make package
echo 'done'
