#! /bin/csh
set path=(/usr/local/bin /usr/local/texbin ~/bin /usr/sbin $path)
setenv PKG_CONFIG_PATH /usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig

cd ~/R/svn/R-devel
svn up
tools/rsync-recommended
cd ~/R/R-devel
make
cd ~/R/R-devel32
make
cd R/packages
./update
/data/gannet/ripley/R/R-devel/bin/Rscript unavailable.R
env DISPLAY=:5 /data/gannet/ripley/R/R-devel/bin/Rscript updates.R
cd tests-devel
make unpack
./script
cat check_log
make package
