#!/bin/csh
setenv DISPLAY :5
limit cputime 300m
setenv _R_CHECK_FORCE_SUGGESTS_ false
setenv LC_CTYPE en_GB.UTF-8
#setenv MYSQL_USER ripley
#setenv POSTGRES_USER ripley
#setenv POSTGRES_HOST localhost
#setenv POSTGRES_DATABASE ripley
setenv RMPI_INCLUDE /usr/include/openmpi-x86_64
setenv RMPI_LIB_PATH /usr/lib64/openmpi/lib
setenv RMPI_TYPE OPENMPI
setenv R_BROWSER false
setenv R_PDFVIEWER false
setenv _R_CHECK_INSTALL_DEPENDS_ true
setenv _R_CHECK_SUGGESTS_ONLY_ true
setenv _R_CHECK_NO_RECOMMENDED_ true
setenv _R_CHECK_DOC_SIZES2_ true
#setenv R_C_BOUNDS_CHECK yes
setenv _R_CHECK_DEPRECATED_DEFUNCT_ true
setenv _R_CHECK_CODE_ASSIGN_TO_GLOBALENV_ true
#setenv _R_CHECK_CODE_ATTACH_ true
setenv _R_CHECK_CODE_DATA_INTO_GLOBALENV_ true

setenv _R_CHECK_ALWAYS_LOG_VIGNETTE_OUTPUT_ true
set path = (/data/blackswan/ripley/extras/bin $path)

setenv R_PARALLEL_PORT random

nohup make -j24 -k check >&! check_log
