#! /bin/csh
pushd ~/R/svn
svn update R-devel R-3-3-branch R-packages R-dev-web
popd
~/R/packages/update
cd ~/R/svn
setenv CRAN_RSYNC ~/R/packages
R-devel/tools/rsync-recommended
R-3-3-branch/tools/rsync-recommended

