#! /bin/csh
svn update svn/R-devel svn/R-3-3-branch svn/R-dev-web svn/R-packages svn/R-docs
cd packages
./update
cd ..
setenv CRAN_RSYNC ~/R/packages
svn/R-devel/tools/rsync-recommended
svn/R-3-3-branch/tools/rsync-recommended

