#!/bin/csh
setenv DISPLAY :5
limit cputime 30m
setenv _R_CHECK_FORCE_SUGGESTS_ false
setenv LC_CTYPE en_GB.UTF-8
#setenv MYSQL_USER ripley
#setenv POSTGRES_USER ripley
#setenv POSTGRES_HOST localhost
#setenv POSTGRES_DATABASE ripley
setenv RMPI_INCLUDE /usr/include/openmpi-x86_64
setenv RMPI_LIB_PATH /usr/lib64/openmpi/lib
setenv RMPI_TYPE OPENMPI
setenv R_BROWSER false
setenv R_PDFVIEWER false
setenv _R_CHECK_INSTALL_DEPENDS_ true
setenv _R_CHECK_SUGGESTS_ONLY_ true
setenv _R_CHECK_NO_RECOMMENDED_ true
setenv _R_CHECK_DOC_SIZES2_ true
#setenv R_C_BOUNDS_CHECK yes
setenv _R_CHECK_DEPRECATED_DEFUNCT_ true
setenv _R_CHECK_CODE_ASSIGN_TO_GLOBALENV_ true
#setenv _R_CHECK_CODE_ATTACH_ true
setenv _R_CHECK_CODE_DATA_INTO_GLOBALENV_ true
setenv _R_CHECK_RD_LINE_WIDTHS_ true
setenv _R_CHECK_FF_CALLS_ registration
setenv _R_CHECK_SCREEN_DEVICE_ warn

set path = (/data/blackswan/ripley/extras/bin $path)

setenv MOSEKLM_LICENSE_FILE "/data/blackswan/ripley/extras/mosek/6/licenses/mosek.lic"
setenv PKG_MOSEKHOME "/data/blackswan/ripley/extras/mosek/6/tools/platform/linux64x86"
setenv PKG_MOSEKLIB "mosek64"
setenv WNHOME /usr/share/wordnet-3.0

#setenv R_PARALLEL_PORT random
setenv _R_CHECK_LIMIT_CORES_ true
setenv MC_CORES 2


nohup make -j32 -k check >&! check_log
