---
title: "Moving to blog.r-project.org"
author: "Tomas Kalibera"
date: 2022-06-30
categories: ["blog location"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

The R blog moves to
[https://blog.r-project.org](https://blog.r-project.org), a more prominent
location, after 37 blog posts (some of them perhaps surprisingly detailed)
and a bit over 4 years.  Please update your bookmarks and RSS readers to use
the new location.

This blog site has been started under https://developer.r-project.org in
March 2018 as a new communication channel for R developers contributing to
the R core implementation.  Most of the blog posts cover selected changes in
R-devel, the development version of R.  They provide a bigger picture for
these changes as well as details, ideas, personal experience and opinions of
the authors.

The blog site has also been used to inform about upcoming bigger changes
impacting R package authors and users.  It has been used to ask for
volunteers from the R community to help with maintaining the core R
implementation.  So far this included asking for help with bug reports, to
which a number of volunteers responded and helped with analyzing and
resolving existing reports.  Some new volunteers contributed patches and one
eventually joined the R Core Team.  More of that help is, and probably
always will be, needed.  The blog post was also used for asking for help
with testing yet unreleased versions of R just before the release, but so
far it seems without success.

Some of the blog posts were of interest for developers of other programming
language runtimes, such as those about issues in numerical libraries not
working with then-recent GNU Fortran due to incorrect calls from C and about
transition to UCRT to get UTF-8 as the native encoding on Windows.

The blog complements
[NEWS](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html), which
lists recent changes in core R implementation, mostly one sentence per
change, but covers all important and most non-trivial changes.  The blog
covers a smaller number of selected bigger changes, but in much more detail,
with personal opinions, and sometimes even in advance.

Many of active contributors to the R core implementation do not use the blog
site much or at all, hence the blogs do not cover some important changes. 
The blog site hence is not at all a fair measure of coding/maintenance
activity happening on the core implementation (one would have to see e.g. 
the versioning system for that).

The [News and notes](https://journal.r-project.org/archive/news-notes.html)
from the R Journal cover all important changes (so a subset of NEWS) in
somewhat more detail and with more background than NEWS, but later after the
changes actually happen, with additional statistics on bug/coding activity. 
The blog has more details, more personal opinions/experience, and covers
things just happening or things still only planned.

The [R-devel mailing list](https://stat.ethz.ch/mailman/listinfo/r-devel) is
a related two-way channel and has been used for follow-ups after at least
one of the rather opinionated blog posts.  Announcements about most
important changes impacting package authors are also sent to that list, and
sometimes pointing to more details in a blog post on this site.

