#! /bin/csh
setenv LC_COLLATE C
setenv PKG_CONFIG_PATH /data/blackswan/ripley/extras/lib64/pkgconfig:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig
set path=(/usr/local/bin /usr/local/texbin /usr/sbin $path /usr/lib64/openmpi/bin)
cd /data/blackswan/ripley/R/svn/R-devel
svn up
tools/rsync-recommended
cd /data/blackswan/ripley/R/R-devel
make
cd /data/blackswan/ripley/R/svn/R-3-2-branch
svn up
tools/rsync-recommended
cd /data/blackswan/ripley/R/R-patched
make
cd /data/blackswan/ripley/R/packages
./update
env DISPLAY=:5 /data/blackswan/ripley/R/R-devel/bin/Rscript updates.R
/data/blackswan/ripley/R/R-devel/bin/Rscript unavailable.R
cd tests-devel
make unpack
./script
cat check_log
#echo 'packaging'
#make package
#echo 'summarizing'
#make summary
echo 'done'
cd ../tests-vg
make backup process
make unpack
./script &
cd ..
env DISPLAY=:5 /data/blackswan/ripley/R/R-patched/bin/Rscript updates.R
/data/blackswan/ripley/R/R-patched/bin/Rscript unavailable.R
cd tests
make unpack
./script
cat check_log

