#! /bin/csh
set path=(/usr/local/bin /usr/local/texbin /usr/sbin $path)
cd ~/R/svn/R-devel
svn up
tools/rsync-recommended
cd ~/R/R-devel
make
cd R/packages
./update
env DISPLAY=:5 /data/blackswan/ripley/R/R-devel/bin/Rscript updates.R
cd tests-devel
make unpack
./script
cat check_log
echo 'packaging'
make package
echo 'summarizing'
make summary
echo 'done'
