#!/bin/csh
setenv DISPLAY :5
setenv TMPDIR ~/R/packages/BioC/2.13/tmp
limit cputime 30m
setenv R_LIBS ~/R/BioC-2.13
setenv _R_CHECK_DEPRECATED_DEFUNCT_ true
#setenv R_C_BOUNDS_CHECK yes
set path = ($path /data/blackswan/ripley/extras/bin)


nohup make -j24 -k check >&! check_log
