#!/bin/csh
setenv DISPLAY :5
limit cputime 30m
setenv _R_CHECK_FORCE_SUGGESTS_ FALSE
setenv LC_CTYPE en_GB.utf8
setenv MYSQL_USER ripley
setenv POSTGRES_USER ripley
setenv POSTGRES_HOST localhost
setenv POSTGRES_DATABASE ripley
#setenv UDUNITS_LIBDIR /usr/lib64
setenv RMPI_INCLUDE /usr/include/openmpi-x86_64
setenv RMPI_LIB_PATH /usr/lib64/openmpi/lib
setenv RMPI_TYPE OPENMPI
setenv R_BROWSER false
setenv R_PDFVIEWER false
nohup make -j12 -k check >&! check_log
