#!/bin/csh
setenv DISPLAY :5
limit cputime 600
setenv _R_CHECK_FORCE_SUGGESTS_ FALSE
setenv _R_CHECK_RD_PARSE_ TRUE
setenv LC_CTYPE en_GB.utf8
#setenv POSTGRES_USER ripley
#setenv POSTGRES_HOST localhost
#setenv POSTGRES_DATABASE ripley
setenv MPI_ROOT /usr/lib64/lam
setenv R_BROWSER false
setenv R_PDFVIEWER false
nohup make -j12 -k >&! script.log
