#!/bin/csh
setenv DISPLAY :5
limit cputime 30m
setenv _R_CHECK_FORCE_SUGGESTS_ false
setenv LC_CTYPE en_GB.utf8
setenv MYSQL_USER ripley
setenv POSTGRES_USER ripley
setenv POSTGRES_HOST localhost
setenv POSTGRES_DATABASE ripley
setenv RMPI_INCLUDE /usr/include/openmpi-x86_64
setenv RMPI_LIB_PATH /usr/lib64/openmpi/lib
setenv RMPI_TYPE OPENMPI
setenv R_BROWSER false
setenv R_PDFVIEWER false
setenv _R_CHECK_INSTALL_DEPENDS_ true
setenv _R_CHECK_SUGGESTS_ONLY_ true
setenv _R_CHECK_NO_RECOMMENDED_ true
#setenv _R_CHECK_DOC_SIZES2_ true
#setenv R_C_BOUNDS_CHECK yes
setenv _R_CHECK_DEPRECATED_DEFUNCT_ true
set path = (/usr/local/gcc48x/bin $path)
setenv R_MAKEVARS_USER ~/.R/Makevars.ASan
setenv ASAN_OPTIONS alloc_dealloc_mismatch=0
setenv ASAN_SYMBOLIZER_PATH /usr/local/bin/llvm-symbolizer

setenv MOSEKLM_LICENSE_FILE "/data/gannet/ripley/Sources/mosek/6/licenses/mosek.lic"
setenv PKG_MOSEKHOME "/data/gannet/ripley/Sources/mosek/6/tools/platform/linux64x86"
setenv PKG_MOSEKLIB "mosek64"
setenv LD_LIBRARY_PATH /usr/local/gcc48x/lib64:$PKG_MOSEKHOME/bin


nohup make -j25 -k check >&! check_log
