#! /bin/csh
set path=(. ~/bin /usr/local/bin /opt/solarisstudio12.3/bin /usr/xpg4/bin /usr/ccs/bin /usr/bin/X11 /usr/openwin/bin /opt/jdk1.7.0_17/bin /bin /usr/bin /usr/sbin /sbin /usr/sfw/bin /usr/local/texlive/2012/bin/i386-solaris /opt/csw/bin /opt/SUNWhpc/HPC8.2.1c/sun/bin)

setenv PKG_CONFIG_PATH /opt/csw/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig
setenv DISPLAY :5
setenv LC_CTYPE en_GB.UTF-8
setenv _R_CHECK_TIMINGS_ 10
setenv _R_CHECK_INSTALL_DEPENDS_ TRUE
setenv _R_CHECK_SUGGESTS_ONLY_ TRUE
setenv _R_CHECK_NO_RECOMMENDED_ TRUE


limit cputime 30m

cd R/packages
./update
Rscript updateBioC.R
~/R/gcc/bin/Rscript updateBioC.R
cd tests32
gmake install
gmake -k -j20 check
echo 'packaging'
make package
echo 'done'
