#! /bin/csh
set path=(. ~/bin /usr/local/bin /opt/solarisstudio12.3/bin /usr/xpg4/bin /usr/ccs/bin /usr/bin/X11 /usr/openwin/bin /opt/jdk1.6.0_27/bin /bin /usr/bin /usr/sbin /sbin /usr/sfw/bin /usr/local/texlive/2011/bin/i386-solaris /opt/csw/bin /opt/SUNWhpc/HPC8.2.1c/sun/bin)

setenv PKG_CONFIG_PATH /opt/csw/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig
setenv DISPLAY :5
setenv LC_CTYPE en_GB.UTF-8
#setenv PVM_ROOT /home/ripley/tools/pvm3
#setenv CPPFLAGS -I/usr/local/include

limit cputime 30m

cd R/packages
./update
cd tests32
gmake install
gmake -k -j20 check
echo 'packaging'
make package
echo 'done'
