#!/bin/sh

ARCH=`arch`
osver=`uname -r`
if [ -z "${oscode}" ]; then
    oscode="darwin"
    case $osver in
	5.*) oscode="puma" ;;
	6.*) oscode="jaguar" ;;
	7.*) oscode="panther" ;;
	8.*) oscode="tiger" ;;
	9.*) oscode="leopard" ;;
	10.*) oscode="snowleopard" ;;
	11.*) oscode="lion" ;;
	12.*) oscode="mountainlion" ;;
        13.*) oscode="mavericks" ;;
        14.*) oscode="yosemite" ;;
        15.*) oscode="el-capitan" ;;
        16.*) oscode="sierra" ;;
	17.*) oscode="high-sierra" ;;
	18.*) oscode="mojave" ;;
    esac
fi

if [ "$ARCH" = i386 ]; then
    ## 10.5+ can run both but arch always returns 32-bit - check if we can use 64-bit instead
    x64=`arch -arch x86_64 sh -c 'echo x86_64'`
    if [ "z$x64" = zx86_64 ]; then
	ARCH=x86_64
    fi
fi

configarch="$ARCH"
texarch="$ARCH"
case "$ARCH" in
    ppc*)
	configarch=powerpc
	texarch=powerpc
	;;
    i?86)
	configarch=i686
	texarch=i386
	;;
esac

: ${TNAME="$oscode-$ARCH"}

# verify that no packagess are being checked
PLOCKPATH=/Builds/packages/lock.checking
if [ -e $PLOCKPATH ]; then
    LPID=`cat $PLOCKPATH`
    if ps -p $PLOCKPATH|grep 'mk\.chk'; then
        echo "**ERROR: package check is in progress, pid $LPID." &1>2
	exit 1
    else
        echo "Stale lock (packages) for pid $LPID, removing"
        rm -f $PLOCKPATH
    fi
fi
