#!/bin/sh

: ${BASE=/Builds/R-builds/nightly}
: ${DEP="${BASE}/deploy"}

OS=tiger
RDS=`cat ${BASE}/builds`
ARS="i386 ppc universal"

for RD in ${RDS}; do
  echo " - ${RD}"
  mkdir -p "${DEP}/${OS}/${RD}/universal" 2>/dev/null
  mv ${BASE}/${RD}-*.dmg ${DEP}/${OS}/${RD}/universal/ 2>/dev/null
  mv ${BASE}/${RD}-${OS}*.tar.gz ${DEP}/${OS}/${RD}/universal/ 2>/dev/null
  gver=`sed -n 's/\(...\).*/\1/p' ${BASE}/${RD}/VERSION 2>/dev/null`
  if [ -n "${gver}" ]; then
      mv ${BASE}/R-GUI-*-${gver}-*.* ${DEP}/${OS}/${RD}/universal/ 2>/dev/null
  fi
  for ARCH in ${ARS}; do
    echo "     ${ARCH}"
    TDIR="${DEP}/${OS}/${RD}/${ARCH}"
    mkdir -p "${TDIR}" 2>/dev/null
    for f in SUCCESS FAILED check.err conf.err build.err check conf build build.log; do
      if [ -e "${BASE}/${OS}-${ARCH}/${RD}.$f" ]; then
        cp "${BASE}/${OS}-${ARCH}/${RD}.$f" "${TDIR}/$f"
      fi
    done
    if [ -e "${BASE}/${OS}-${ARCH}/build.log" ]; then
      cp "${BASE}/${OS}-${ARCH}/build.log" "${TDIR}/build.log"
    fi
  done
done

