#!/bin/sh

: ${BASE=/Builds/R-builds/nightly}
: ${RDIRS=`cat $BASE/builds $BASE/builds.aux`}

WD=`pwd`
cd ${BASE}
OS=tiger

for rd in ${RDIRS}; do
    rm -f `ls -d ${rd}-*.dmg 2>/dev/null|sort -r|sed -n '2,99p'`
    rm -f `ls -d deploy/${OS}/${rd}/universal/${rd}-*.dmg 2>/dev/null|sort -r|sed -n '2,99p'`
    rm -f `ls -d deploy/${OS}/${rd}/universal/${rd}-*.tar.gz 2>/dev/null|sort -r|sed -n '2,99p'`
done

for bst in Deployment; do
    for ver in 2.4 2.5 2.6; do
	rm -f `ls -d R-GUI-*-${ver}-${bst}.tar.gz 2>/dev/null|sort -r|sed -n '2,99p'`
	rm -f `ls -d R-GUI-*-${ver}-${bst}.dmg 2>/dev/null|sort -r|sed -n '2,99p'`
	rm -f `ls -d deploy/${OS}/*/universal/R-GUI-*-${ver}-${bst}.tar.gz 2>/dev/null|sort -r|sed -n '2,99p'`
	rm -f `ls -d deploy/${OS}/*/universal/R-GUI-*-${ver}-${bst}.dmg 2>/dev/null|sort -r|sed -n '2,99p'`
    done
done

cd ${WD}
