#!/bin/sh

: ${BASE=/Builds/R-builds/nightly}
: ${RDIRS=`cat $BASE/builds`}

WD=`pwd`

for rd in ${RDIRS}; do
    rm -f `ls -d ${rd}-*.dmg|sed -n '2,99p'`
done

for bst in Deployment; do
    for ver in 2.4 2.5; do
	rm -f `ls -d R-GUI-*-${ver}-${bst}.tar.gz|sed -n '2,99p'`
    done
done

cd ${WD}
