#!/bin/sh

BASE=/Builds/R-builds/nightly
export BASE

: ${server=r}

#GUIDMG=`sort $BASE/GUIs|uniq|sed 's/.*/&.dmg/'`
#ssh $server '/usr/bin/rm -f wwwfiles/R??-branch*.dmg wwwfiles/R-*.dmg'
FS=`ls $BASE/web/index.html $BASE/deploy/*/*/universal/R*.pkg $BASE/deploy/*/*/universal/R*-universal.tar.gz $BASE/web/log-* $BASE/deploy/*/*/universal/R*.dmg`
for fn in $FS; do
    ok=`find "$fn" -mtime -1`
    if [ -n "$ok" ]; then
	scp "$fn" $server:wwwfiles/
    fi
done

## hack since mavericks failed to sign                                                                                  
                                  
PKGS=`ls $BASE/deploy/mavericks/*/*mavericks.pkg`
$BASE/unlock-sign
for pkg in $PKGS; do
    spkg=`echo $pkg | sed 's:mavericks.pkg:mavericks-signed.pkg:'`
    if [ ! -e "$spkg" ]; then
        xcrun productsign --sign 'Developer ID Installer' $pkg $spkg
    fi
done

rsync -av --delete-after $BASE/deploy/snowleopard/ r:wwwfiles/snowleopard/
rsync -av --delete-after $BASE/deploy/mavericks/ r:wwwfiles/mavericks/
ssh $server 'wwwfiles/rmold'

# scp web/index.html r:wwwfiles/
