.SUFFICES:
.SUFFICES: .out .log

BB-OPTS = --no-tests
Bergm-OPTS = --no-examples
DSL-OPTS = --no-vignettes
IsoGene-OPTS = --no-examples
NCBI2R-OPTS = --no-examples
PAGI-OPTS = --no-rebuild-vignettes
# runs away sometimes
RNCEP-OPTS = --no-examples
# Rook-OPTS = --no-examples
SNPRelate-OPTS = --no-examples
TSdata-OPTS = --no-vignettes
VGAM-OPTS = --no-examples
abc-OPTS = --no-vignettes
amei-OPTS = --no-vignettes
# fails
anchors-OPTS = --no-rebuild-vignettes
atmi-OPTS = --no-examples
# very slow web access
celsius-OPTS = --no-examples
crimCV-OPTS = --no-examples
dynGraph-OPTS = --no-examples
# often crashes
fractal-OPTS = --no-examples
# need Perl
gdata-OPTS = --no-examples --no-tests
# x64 infinite-loops
lokern-OPTS = --no-tests
lossDev-OPTS = --no-vignettes
# mcmc-OPTS = --no-vignettes
# hangs sometimes
misc3d-OPTS = --no-examples
# very slow
mlmRev-OPTS = --no-examples
# latex step fails.
quantreg-OPTS = --no-rebuild-vignettes
rWMBAT-OPTS = --no-examples
# very slow
rebmix-OPTS = --no-vignettes
speff2trial-OPTS = --no-examples
spikeSlabGAM-OPTS = --no-vignettes
surveillance-OPTS = --no-examples
tgp-OPTS = --no-examples --no-vignettes

## crash and remain running.
glmpath-OPTS = --no-examples
seewave-OPTS = --no-examples

all:
	@make --no-print-directory update install
	@make --no-print-directory -j4 -k check

LOGS=${shell ls *.log}
check: $(LOGS:.log=.out)

install:
	@Rscript.exe manip.R LC_COLLATE=C

installn reinstall:
	@Rscript.exe reinstall.R LC_COLLATE=C

clean:
	find * -maxdepth 0 -type d -exec rm -rf {} \;
	rm -f *.in

veryclean: clean
	rm -f *.out

update:
	@(cd ../packages; sh update)
