#!/bin/sh

ROOT="$1"
if [ -z "$1" ]; then
    echo "ERROR: root must be specified" >&2
    exit 1
fi

if [ -z "$VER" ]; then
    echo "ERROR: VER is not set" >&2
    exit 1
fi

if [ -z "$GUIVER" ]; then
    echo "ERROR: GUIVER is not set" >&2
    exit 1
fi

if [ ! -e "$ROOT/template/dist.plist" ]; then
    echo "ERROR: invalid root, $ROOT/template/dist.plist is missing" >&2
    exit 1
fi

for i in `find "$ROOT/template" -name \*plist -or -name \*rtf`; do
    dst=`echo $i | sed s:/template::`
    echo $i '->' $dst
    sed -e "s/%VER%/$VER/g" -e "s/%VERFULL%/$VERFULL/g" -e "s/%GUIVER%/$GUIVER/g" $i > $dst
done
