#!/bin/csh
setenv DISPLAY :5
limit cputime 10m
setenv _R_CHECK_FORCE_SUGGESTS_ FALSE
setenv LC_CTYPE en_GB
setenv RMPI_INCLUDE /usr/include/openmpi-x86_64
setenv RMPI_LIB_PATH /usr/lib64/openmpi/lib
setenv RMPI_TYPE OPENMPI
setenv R_BROWSER false
setenv R_PDFVIEWER false
setenv OMP_NUM_THREADS 2
setenv _R_CHECK_DEPRECATED_DEFUNCT_ true
setenv _R_CHECK_CODE_ASSIGN_TO_GLOBALENV_ true
setenv _R_CHECK_CODE_ATTACH_ true
setenv _R_CHECK_CODE_DATA_INTO_GLOBALENV_ true
setenv _R_CHECK_TIMINGS_ 10
setenv _R_CHECK_DOC_SIZES2_ true
setenv R_PARALLEL_PORT random

setenv MOSEKLM_LICENSE_FILE "/home/ripley/Sources/mosek/6/licenses/mosek.lic"
setenv PKG_MOSEKHOME "/home/ripley/Sources/mosek/6/tools/platform/linux64x86"
setenv PKG_MOSEKLIB "mosek64"
setenv LD_LIBRARY_PATH $PKG_MOSEKHOME/bin

nohup make -j8 -k check >&! check_log
