#! /bin/csh
cd ~/R
./update
cd ~/R/R-devel
make -j10
./bin/Rscript -e 'update.packages(.Library, ask = F)'
cd R/packages
~/R/R-devel/bin/Rscript unavailable.R
env DISPLAY=:5 NOAWT=1 RMPI_TYPE=OPENMPI RGL_USE_NULL=true ~/R/R-devel/bin/Rscript updates.R
cd tests-devel
make unpack
./script
#make package
