#! /bin/csh
cd ~/R
./update
cd ~/R/R-patched
make
cd R/packages
~/R/R-patched/bin/Rscript unavailable.R
env DISPLAY=:5 NOAWT=1 RMPI_TYPE=OPENMPI RGL_USE_NULL=true ~/R/R-patched/bin/Rscript updates.R
cd tests
make unpack
./script
