#! /bin/csh
cd ~/R
./update
cd ~/R/R-patched
make -j10
cd ~/R/R-devel
make -j10
cd R/packages
~/R/R-patched/bin/Rscript unavailable.R
~/R/R-devel/bin/Rscript unavailable.R
env DISPLAY=:5 NOAWT=1 RMPI_TYPE=OPENMPI RGL_USE_NULL=true ~/R/R-patched/bin/Rscript updates.R
env DISPLAY=:5 NOAWT=1 RMPI_TYPE=OPENMPI RGL_USE_NULL=true ~/R/R-devel/bin/Rscript updates.R
cd tests-devel
make unpack
./script
make package
cd ../tests
make unpack
./script
