#! /bin/csh
cd ~/R
./update
cd ~/R/R-patched
make
cd ~/R/R-devel
make
cd ~/R/R-clang
make
cd R/packages
Rscript unavailable.R
env DISPLAY=:5 NOAWT=1 RMPI_TYPE=OPENMPI Rscript updates.R
env DISPLAY=:5 NOAWT=1 RMPI_TYPE=OPENMPI ~/R/R-devel/bin/Rscript updateBioC.R
cd tests
make unpack rgl-make
./script
cd ../tests-clang
make unpack rgl-make
./script

