#! /bin/csh
pushd ~/R/svn
svn update R-devel R-3-3-branch R-packages R-dev-web R-docs
popd
~/R/packages/update
cd ~/R
setenv CRAN_RSYNC /Users/ripley/R
svn/R-devel/tools/rsync-recommended
svn/R-3-3-branch/tools/rsync-recommended
