---
title: "RSMF: Enabling the Next Generation of Contributors to R"
author: "Heather Turner"
date: 2025-12-17
categories: ["External Contributions", "R Core", "R Foundation"]
tags: ["mentoring", "development infrastructure", "governance"]

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

The Software Sustainability Institute (UK) has awarded a grant of £500k (\~650k USD) under the [Research Software Maintenance Fund](https://www.software.ac.uk/rsmf-round-1-projects), to the project *Enabling the Next Generation of Contributors to R*.

The project is co-led by research software engineers at the University of Birmingham ([Heather Turner](https://www.linkedin.com/in/heathrturnr) and [Ella Kaye](https://ellakaye.co.uk/about.html)), members of the R Core Team ([Simon Urbanek](https://profiles.auckland.ac.nz/s-urbanek) and [Peter Dalgaard](https://www.cbs.dk/en/research/department-finance/peter-dalgaard)), and a team of academic/freelance R developers ([Gabe Becker](https://github.com/gmbecker), [Kylie Bemis](https://www.khoury.northeastern.edu/people/kylie-ariel-bemis/), [Mikael Jagan](https://github.com/jaganmn), [Jeroen Ooms](https://github.com/jeroen)). The project will receive further support from the [R Consortium](https://r-consortium.org/) (developer events and travel support), the [R Foundation](https://www.r-project.org/foundation/) (travel support for core developers), and several companies dedicating staff time: [Posit](https://posit.co), [A2-Ai](https://a2-ai.com/), and [Google](https://about.google/).

The overall aim is to address the challenge of sustaining the R Project. This will be achieved through work on four areas described below.

## Establishing a Cohort of Expert Contributors

A cohort of expert developers (project co-leads: Gabe Becker, Kylie Bemis, Mikael Jagan, Jeroen Ooms; partner-sponsored developers: [Kevin Ushey](https://www.linkedin.com/in/kevin-ushey-33a35542/) and the tidyverse team [Posit], [Mossa Reimert](https://www.linkedin.com/in/cgmossa) [A2-Ai], [Mike Chirico](https://www.linkedin.com/in/michael-chirico-9b6b0527/) [Google]) will be mentored by members of the R Core Team (including Simon Urbanek, Peter Dalgaard, [Paul Murrell](https://www.stat.auckland.ac.nz/~paul/), [Deepayan Sarkar](https://www.isid.ac.in/~deepayan/), [Luke Tierney](https://stat.uiowa.edu/people/luke-tierney) and [Michael Lawrence](https://www.linkedin.com/in/michael-lawrence-74a9b482/)). They will work on projects supporting the development or maintenance of R, as well as helping to triage and fix bugs.

Example projects include broader use of GitHub actions, using generative AI to enhance the CRAN checks, and improved testing of R-devel.

## Supporting Broader Engagement

Heather Turner and Ella Kaye will lead activities to support broader engagement from both new and experienced contributors. This includes developing a code of conduct for the R Project, exploring alternative platforms for code development that provide an easier on-ramp for contributors, and piloting a process for discussion of enhancement proposals. The team will sustain recent initiatives of the R Contribution Working Group: organizing outreach events such as [R Dev Days](https://contributor.r-project.org/events/r-dev-days/) and maintaining documentation and infrastructure created to facilitate contribution.

The Brazil-based consultancy, [R6 Estatística e Treinamentos](https://www.rseis.com.br/), will work to improve the integration of translations contributed via Weblate, mentored by the current Weblate admins Mike Chirico and [Gergely Daróczi](https://economics.ceu.edu/people/gergely-daroczi).

## Improving Communication

The third area of focus will be to improve communication, especially between the R Core Team and the wider community. This will involve adopting modern open source tools to facilitate discussions related to R contribution and expanding the use of the R Blog and R Foundation social media accounts to engage R users in the process of R development.

## Sustaining the R Foundation

Finally, the project will address sustainability of the R Foundation, the non-profit behind R. On the governance side, this will involve proposing a new organisational structure and modernising election procedures to encourage wider participation. On the financial side, work will focus on diversifying income streams. This is important because the RSMF grant, similar to the
[recent investment in the R Project by the Sovereign Tech Agency](https://www.sovereign.tech/tech/r-project) recently received by the R Foundation, is only intended for short-term funding so there is a continued need to raise funds for long-term sustainability.

## Acknowledgements

The University of Birmingham is providing institutional support for this project. [Aad van Moorsel](https://www.birmingham.ac.uk/staff/profiles/computer-science/academic-staff/van-moorsel-aad), Head of the School of Computer Science, is providing overall leadership, while [Adrian Garcia](https://www.birmingham.ac.uk/research/arc/rsg/staff/adrian-garcia), Research Software Engineering Service Lead, is providing managerial support.  

The Software Sustainability Institute is supported by UK Research and Innovation (UKRI), a non-departmental public body sponsored by the UK government.

Recent initiatives of the R Contribution Working Group have been largely supported by Heather Turner's research software engineering fellowship from the UK Engineering and Physical Sciences Research Council, EP/V052128/1.

## Links

- Research Software Maintenance Fund Round 1 Results: [https://www.software.ac.uk/ssi-awards-funding-13-critical-projects-through-research-software-maintenance-fund-round-1](https://www.software.ac.uk/ssi-awards-funding-13-critical-projects-through-research-software-maintenance-fund-round-1)  
- R Contributors Subsite: [https://contributor.r-project.org/](https://contributor.r-project.org/)  
- R Foundation Donations: [https://www.r-project.org/foundation/donations.html](https://www.r-project.org/foundation/donations.html)
