---
title: "Sovereign Tech Fund Project: Milestone 1"
author: "Simon Urbanek and Tomáš Kalibera"
date: 2026-06-02
categories: ["External Contributions", "User-visible Behavior", "Internals"]
tags: ["debugging", "bugs", "bugzilla", "STF"]

---

## Sovereign Tech Fund (STF) Project
Starting in mid 2025, the R Project has been working on 
a series of work packages to improve the long-term stability of the R
ecosystem. The project is supported by an investment from the [Sovereign Tech Agency](https://www.sovereign.tech/), under their [Sovereign Tech Fund](https://www.sovereign.tech/tech/r-project). In a series of blog posts, some details about
the achieved results will be shared with the public, starting with Milestone
1. These blog posts are a tribute to the late [Tomáš Kalibera](https://www.r-project.org/doc/obit/tomas.html), who
continued working on this project during his last months. 

## Milestone 1: Triage and reduce backlog of bugs

At the beginning of the project, base R had over $600$ open bugs in its issue
tracking system, a Bugzilla instance hosted at <https://bugs.r-project.org>. The work for this milestone involved systematically analysing the backlog of bug reports:
identifying those that were not relevant and could be closed; 
researching solutions for significant bugs, and implementing fixes that
resolved some of those issues. The quality of the codebase was thus improved,
and the visibility of significant bugs in the bug tracker was increased, easing future bug management for the maintainers of R.

## Milestone Results

On July 31, 2025, there were $624$ open bug reports in the R Project
Bugzilla. This number was reduced
to $467$ open bug reports on October 1, 2025, which is a reduction of
about $25\%$. Bugs no longer relevant or not reproducible/actionable
were closed with a short explanation. Invalid bugs and issues not
feasible to fix/not worth fixing, as well as wishlist items not worth
adding, were closed with a detailed explanation, so that the people
reporting the bugs would not be discouraged from further contribution, but
instead learn how to contribute better. Some remaining relevant bugs were
fixed, including some bugs that were many years old. In addition, comments were added to
some (still) open bugs, in an attempt to get further
information from the reporters or expert comments, increasing the
chances they could be resolved, soon. This effort has been noticed by
package developers who reported some of the bugs and positively
reflected on the R-devel mailing list:

> _"Maybe others will share in my astonishment seeing that Tomas Kalibera has
since Aug 1 closed ~80 bugs on R's Bugzilla, in all cases providing quite
thoughtful and instructive explanation."_  
> - Mikael Jagan, full post: <https://stat.ethz.ch/pipermail/r-devel/2025-August/084155.html>

> _"I too share the positive feelings about this effort.
The detailed explanations clearly helps me learn, regardless of the
fact that sometimes the answer is not the desired one."_  
> - Lluís Revilla, full post <https://stat.ethz.ch/pipermail/r-devel/2025-August/084157.html>

The results of the work are publicly available on
<https://bugs.r-project.org>, where the advanced search feature allows
to focus on specific activity in the two months allocated for Milestone 1, the
result is available as
<https://bugs.r-project.org/buglist.cgi?chfield=resolution&chfieldfrom=2025-08-01&chfieldto=2025-09-30&order=Last%20Changed&product=R&query_format=advanced>.
