---
title: "Rousseuw Prize 2026 Awarded to the R Project"
author: "Martyn Plummer"
date: 2026-06-17
categories: ["R Core"]
tags: ["prizes"]

---

The [Rousseeuw Prize for Statistics](https://rousseeuwprize.org) is a
biennial prize that awards pioneering work in statistical
methodology. The prize recognizes a statistical innovation, that is,
an outstanding contribution or tool that has had significant impact
and found wide application in statistical practice.

Five members of the R Core Team have been awarded the Rousseeuw Prize
for Statistics for their decades of work building and maintaining the
R Project. The 2026 laureates are:

- Prof. Brian Ripley, University of Oxford, United Kingdom
- Prof. Martin Maechler, ETH Zurich, Switzerland
- Prof. Kurt Hornik, Vienna University of Economics and Business, Austria
- Prof. Peter Dalgaard, Copenhagen Business School, Denmark
- Prof. Luke Tierney, University of Iowa, United States

Half of the prize money goes to the five laureates because they are
deemed to have made the longest sustained contributions, and half goes
to the other members of the R Core Team.

The [prize announcement](https://rousseeuwprize.org/2026) explains the
choice of the R Project:

> It is through the combination of providing a high quality base system, and mechanisms and infrastructure for extending this base system, that R has become the common language of statistics and data science. Methodological innovations in modern statistics are typically obtained using R and freely provided as R extension packages, making them accessible to everyone. By keeping R free and open-source under the GNU General Public License, the R Core Team removed many of the financial barriers that have historically limited access to advanced analytics software. Due to this increased accessibility, millions of users including researchers, students, hospitals, public health organizations, and governments around the world are able to utilize the same statistical tools regardless of institutional resources, also in developing countries. Their work has transformed statistics and data science from many isolated workers writing long programs into an enthusiastic collaborative community where ideas and code are easily shared and built upon.

> The efforts of the R Core Team members have been driven by the vision that everybody should have free access to the state-of-the-art of statistical methods, and therefore be able to perform better data analysis and decision making. This involves spending huge amounts of time on the ongoing work of adapting R to evolving hardware and software environments. The fact that the main R Core Team reference has been cited over 343,000 times on Semantic Scholar, and the quantity and quality of available extension packages shows that the time investment of the R Core Team has clearly paid off, with huge benefits for the wide community of users.
